config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/search', to: 'users#search'
  get '/searchresults', to: 'users#searchresults'
  get '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  post '/loginverify', to: 'users#loginverify'
  post '/create', to: 'users#create'

  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find_by(
			params[:user_id]
			)
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to "/posts/show"
		else
			render :back
		end
	end

	def post_params
		params.require(:post).permit(:content, :user_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def destroy
  session[:user_id] = nil
  session.clear
  render :logout, :notice => "Logged out!"
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  @user.update(user_params)
  redirect_to user_path @user
end

def login
end

def loginverify
  result = User.all.where(
    email: params[:email],
    password: params[:password]).first

  if result
    session[:user_id] = result.id
    redirect_to "/users/show"

  else
    flash[:alert] = "Invalid email or password"
    redirect_to '/login'
  end
end

def logout
  session[:user_id] = nil
  session.clear

  redirect_to root
end

def new
  @user = User.new
end

def create
  result = User.create(user_params)
  if result && !result.id.nil?
    redirect_to "/users/show" 
  else
    flash[:alert] = result.errors.full_messages
    redirect_to "/users/new"
  end
end

def show
  @user = User.find_by(
    id: session[:user_id]
    )
end

def search
end

def searchresults
  @query = params[:fname]
  @users = User.where("fname LIKE ?", "%#{params[:fname]}%")

end

private

def user_params
  params.require(:user).permit(:fname, :lname, :email, :password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= link_to("login", login_path(@user)) %>
<%= link_to("new user", new_user_path(@user)) %>
<%= link_to("search", search_path(@user)) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>Hello, World!</p>
<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<%= form_for @post, :url => {:action => "create"} do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>
<p class="button"><%= submit_tag "Post" %></p>
<% end %>

app/views/posts/show.html.erb
<p>
	<p><%= @post.content %></p>
</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= form_for(@user, method: :put) do |f| %>
<p>
	<%=f.label :fname %>
	<%=f.text_field :fname %>
</p>

<p>
	<%=f.label :lname %>
	<%=f.text_field :lname %>
</p>

<%=f.submit %>
<% end %>

app/views/users/login.html.erb
<%= form_tag '/loginverify' do %>
	<%= label_tag 'email' %>
	<%= text_field_tag 'email' %>

	<%= label_tag 'password' %>
	<%= text_field_tag 'password' %>

	<%= submit_tag 'submit' %>
<% end %>

app/views/users/logout.html.erb
<p>
	YOU HAVE LOGGED OUT
</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<p>
	<%=f.label :fname %>
	<%=f.text_field :fname %>
</p>
<p>
	<%=f.label :lname %>
	<%=f.text_field :lname %>
</p>
<p>
	<%=f.label :email %>
	<%=f.text_field :email %>
</p>
<p>
	<%=f.label :password %>
	<%=f.text_field :password %>
</p>
<%=f.submit :create %>
<% end %>

<%= link_to("login", login_path(@user)) %>

app/views/users/search.html.erb
<%= form_tag('/searchresults', method: :get) do %>
	<%= label_tag 'fname' %>
	<%= text_field_tag 'fname' %>

	<%= label_tag 'lname' %>
	<%= text_field_tag 'lname' %>

	<%= label_tag 'email' %>
	<%= text_field_tag 'email' %>

	<%= submit_tag 'submit' %>
<% end %>

app/views/users/searchresults.html.erb
<p>Here are your search results. for query: "<%= @query %>"</p>
<ul>
<% @users.each do |u| %>
	<li>
		<%= link_to("#{u.fname} #{u.lname}", user_path(u)) %>
	</li>
<% end %>
</ul>

app/views/users/show.html.erb
<% if @user %>
	<p> You are logged in! Hi <%= @user.fname %> </p>
<% else %>
	<p> Sorry, I don't know who you are. Please login. </p>
<% end %>

<%= link_to("login", login_path(@user)) %>
<%= link_to("post", new_post_path(@post)) %>